{{ if lookPath "gdb" }}
[".config/gdb/gef.py"]
type = "file"
url = "https://gef.blah.cat/py"
refreshPeriod = "24h"
{{ end }}

{{ if lookPath "tmux" }}
[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "24h"
{{ end }}

{{ if lookPath "vim" }}
{{ if ne .chezmoi.os "windows" -}}
[".vim/autoload/plug.vim"]
{{ else -}}
["vimfiles/autoload/plug.vim"]
{{ end -}}
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "24h"
{{ end }}

{{ if lookPath "zsh" }}
{{ $antibodyVersion := (gitHubLatestRelease "getantibody/antibody").TagName -}}
[".local/bin/antibody"]
type = "archive-file"
url = "https://github.com/getantibody/antibody/releases/download/{{ $antibodyVersion }}/antibody_Linux_x86_64.tar.gz"
path = "antibody"
[".local/share/lscolors.sh"]
type = "file"
url = "https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/lscolors.sh"
refreshPeriod = "24h"
{{ end }}
