#!/bin/bash

set -eo pipefail
mkdir -p ~/.config
mkdir -p ~/.local/bin

info() {
    printf "\e[1m\e[96mInstalling %s...\e[m\n" $1
}

inst() {
    [[ -f $2 ]] && mv -f $2 $2.bak
    ln -sf ~+/$1 $2
}

pull() {
    git clone --depth 1 $1 $2 2>/dev/null || git -C $2 pull
}

info gitconfig
inst gitconfig ~/.gitconfig
inst gitignore ~/.config/gitignore
curl -fsLo ~/.local/bin/diff-so-fancy git.io/vpxB1
chmod +x ~/.local/bin/diff-so-fancy
inst gitconfig.nix ~/.config/gitconfig.local

info cheat.sh
curl -fso ~/.local/bin/cht.sh https://cht.sh/:cht.sh
chmod +x ~/.local/bin/cht.sh

info pyenv
mkdir -p ~/.config/pip
inst pip.conf ~/.config/pip/pip.conf
export PYENV_ROOT=~/.local/share/pyenv
curl -fsL git.io/install-pyenv | bash
[[ $(command -v pyenv) ]] && pyenv update

if [[ $(command -v gdb) ]]; then
    info gdbinit
    [[ -f ~/.gdbinit ]] && mv -f ~/.gdbinit ~/.gdbinit.bak
    curl -fsLo ~/.gdbinit git.io/.gdbinit
fi

if [[ $(command -v tmux) ]]; then
    info tmux.conf
    pull https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    inst tmux.conf ~/.tmux.conf
    ~/.tmux/plugins/tpm/bin/install_plugins
    ~/.tmux/plugins/tpm/bin/update_plugins all
fi

if [[ $(command -v zsh) ]]; then
    info zshrc
    inst zshenv ~/.zshenv
    curl -fsL git.io/vb6iL | sh
    zsh -c "antibody bundle < zsh_plugins.txt" &>/dev/null || true
    zsh -c "antibody bundle < zsh_plugins.txt" >~/.config/zsh_plugins.sh
    curl -fsLo ~/.dircolors git.io/vpOBP
    inst zshrc ~/.zshrc

    if [[ $(uname -m) == x86_64 ]]; then
        [[ $TMPDIR ]] || TMPDIR="$(mktemp -d)"
        URL=$(curl -fs https://api.github.com/repos/ogham/exa/releases/latest \
            | grep -Eo "https://[[:alnum:]_./-]+linux-x86_64[0-9.-]+\.zip")
        curl -fsLo "$TMPDIR"/exa.zip "$URL"
        unzip "$TMPDIR"/exa.zip -d ~/.local/bin >/dev/null
        mv -f ~/.local/bin/exa-* ~/.local/bin/exa
    fi
fi

if [[ $(command -v vim) ]]; then
    info vimrc
    curl -fsLo ~/.vim/autoload/plug.vim --create-dirs git.io/VgrSsw
    inst vimrc ~/.vimrc
    inst ycm_extra_conf.py ~/.config/ycm_extra_conf.py
    vim +PlugClean! +PlugUpdate +qa

    # fzf
    curl -fsLo ~/.local/bin/fshow git.io/vpxBg
    chmod +x ~/.local/bin/fshow
fi
