#!/bin/bash

set -eo pipefail
mkdir -p ~/.config
mkdir -p ~/.local/bin

info() {
    printf "\e[34mInstalling %s ...\e[m\n" $1
}

inst() {
    if [[ -h $2 ]]; then
        rm -f $2
    elif [[ -e $2 ]]; then
        mv -f $2 $2.old
    fi
    ln -s ~+/$1 $2
}

pull() {
    git clone --depth 1 $1 $2 2>/dev/null || git -C $2 pull
}

info gitconfig
inst git ~/.config/git
if [[ -n $(command -v delta) ]]; then
    inst gitconfig.delta ~/.config/gitconfig.local
else
    touch ~/.config/gitconfig.local
fi

info dir_colors
curl -fsLo ~/.dircolors git.io/vFp6j

info pythonrc
inst pythonrc ~/.config/pythonrc
inst pip ~/.config/pip

if [[ -n $(command -v gdb) ]]; then
    info gdbinit
    curl -fsL git.io/JfBXG | bash
fi

if [[ -n $(command -v tmux) ]]; then
    info tmux.conf
    inst tmux/tmux.conf ~/.tmux.conf
    inst tmux/tmux-powerlinerc ~/.tmux-powerlinerc
    mkdir -p ~/.tmux
    inst tmux/segments ~/.tmux/segments
    inst tmux/themes ~/.tmux/themes
    pull https://github.com/erikw/tmux-powerline ~/.tmux/tmux-powerline
    pull https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    printf "\e[36mSee https://github.com/tmux-plugins/tpm#key-bindings to"
    printf " complete the installation.\e[m\n" $1
fi

if [[ -n $(command -v vim) ]]; then
    info vimrc
    inst vimrc ~/.vimrc
    curl -fsLo ~/.vim/autoload/plug.vim --create-dirs git.io/VgrSsw
    vim +PlugClean! +PlugUpdate +qa

    # fzf
    curl -fsLo ~/.local/bin/fshow git.io/vpxBg
    chmod +x ~/.local/bin/fshow
fi

if [[ -n $(command -v zsh) ]]; then
    info zshrc
    inst zsh/zshenv ~/.zshenv
    mkdir -p ~/.config/zsh
    inst zsh/colored-man-pages.zsh ~/.config/zsh/colored-man-pages.zsh
    inst zsh/p10k.zsh ~/.p10k.zsh
    curl -fsL git.io/antibody | sh -s -- -b ~/.local/bin
    zsh -c "antibody bundle <zsh/zsh_plugins.txt" &>/dev/null || true
    zsh -c "antibody bundle <zsh/zsh_plugins.txt" >~/.config/zsh/zsh_plugins.sh
    inst zsh/zshrc ~/.zshrc

    if [[ $(uname -m) == x86_64 ]]; then
        [[ $TMPDIR ]] || TMPDIR="$(mktemp -d)"
        URL=$(curl -fs https://api.github.com/repos/ogham/exa/releases/latest \
            | grep -Eo "https://[[:alnum:]_./-]+linux-x86_64-v[0-9.]+\.zip")
        curl -fsLo "$TMPDIR"/exa.zip "$URL"
        unzip -uo "$TMPDIR"/exa.zip -d ~/.local >/dev/null
    fi
fi

printf "\e[32mDone!\e[m\n"
