#!/bin/bash

set -eo pipefail
mkdir -p ~/.config
mkdir -p ~/.local/bin

info() {
    printf "\e[1;34mInstalling %s ...\e[m\n" $1
}

inst() {
    if [[ -e $2 ]]; then
        if [[ -h $2 ]]; then
            rm -f $2
        else
            mv -f $2 $2.bak
        fi
    fi
    ln -s ~+/$1 $2
}

pull() {
    git clone --depth 1 $1 $2 2>/dev/null || git -C $2 pull
}

info gitconfig
inst git ~/.config/git
curl -fsLo ~/.local/bin/diff-so-fancy git.io/vpxB1
chmod +x ~/.local/bin/diff-so-fancy
inst gitconfig.unix ~/.config/gitconfig.local

info cheat.sh
curl -fso ~/.local/bin/cht.sh https://cht.sh/:cht.sh
chmod +x ~/.local/bin/cht.sh

info pythonrc
inst pythonrc ~/.config/pythonrc
inst pip ~/.config/pip

if [[ -n $(command -v gdb) ]]; then
    info gdbinit
    if [[ -e ~/.gdbinit ]]; then
        if [[ -h ~/.gdbinit ]]; then
            rm -f ~/.gdbinit
        else
            mv -f ~/.gdbinit ~/.gdbinit.bak
        fi
    fi
    curl -fsLo ~/.gdbinit git.io/.gdbinit
fi

if [[ -n $(command -v tmux) ]]; then
    info tmux.conf
    inst tmux.conf ~/.tmux.conf
    inst tmux-powerlinerc ~/.tmux-powerlinerc
    mkdir -p ~/.tmux
    inst tmux/segments ~/.tmux/segments
    inst tmux/themes ~/.tmux/themes
    pull https://github.com/erikw/tmux-powerline ~/.tmux/tmux-powerline
    pull https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    printf "\e[1;36mSee https://github.com/tmux-plugins/tpm#key-bindings to"
    printf " complete the installation.\e[m\n" $1
fi

if [[ -n $(command -v vim) ]]; then
    info vimrc
    inst vimrc ~/.vimrc
    curl -fsLo ~/.vim/autoload/plug.vim --create-dirs git.io/VgrSsw
    inst ycm_extra_conf.py ~/.vim/.ycm_extra_conf.py
    vim +PlugClean! +PlugUpdate +qa

    # fzf
    curl -fsLo ~/.local/bin/fshow git.io/vpxBg
    chmod +x ~/.local/bin/fshow
fi

if [[ -n $(command -v zsh) ]]; then
    info zshrc
    inst zshenv ~/.zshenv
    curl -fsL git.io/antibody | sh -s -- -b ~/.local/bin
    zsh -c "antibody bundle < zsh_plugins.txt" &>/dev/null || true
    zsh -c "antibody bundle < zsh_plugins.txt" >~/.config/zsh_plugins.sh
    inst zshrc ~/.zshrc

    if [[ $(uname -m) == x86_64 ]]; then
        [[ $TMPDIR ]] || TMPDIR="$(mktemp -d)"
        URL=$(curl -fs https://api.github.com/repos/ogham/exa/releases/latest \
            | grep -Eo "https://[[:alnum:]_./-]+linux-x86_64[0-9.-]+\.zip")
        curl -fsLo "$TMPDIR"/exa.zip "$URL"
        unzip "$TMPDIR"/exa.zip -d ~/.local/bin >/dev/null
        mv -f ~/.local/bin/exa-* ~/.local/bin/exa
    fi
fi

printf "\e[1;36mDone!\e[m\n"
